import type { Metadata } from "next";
import "./globals.css";
import HeaderBase from "@/components/HeaderBase";
import { onest } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <HeaderBase />
        {children}
      </body>
    </html>
  );
}
